### ISSUE TITLE
How to make treeview working in es6

### ISSUE THREAD

**Issue by rafikahamed** [jonmiles/react-bootstrap-treeview#16]
I tried to convert the tree view code as per ES6 concept, we are facing the below issue.

Warning: validateDOMNesting(...): <li> cannot appear as a descendant of <li>. See TreeNode > li > ... > TreeNode > li.

I tried with below github link code as well, but the tree structure its not in <li>, its displying like <ul> and <li> format, when i am trying to convert the code its giving  validateDOMNesting(...):  error, but the requirement its we want to display all the tree node in <li>format.

https://github.com/elifTech/treeview-react-bootstrap.git 

Could you please help us to fixed the above issue.

**Comment by jonmiles** [comment]
This was a prototype project. Beyond that, it's open source and I do not provide support, or fix other people code... too many requests like this, is the reason I no longer maintain these projects.
