### ISSUE TITLE
npm ERR when bower not found

### ISSUE THREAD

**Issue by chuchengcao** [jonmiles/react-bootstrap-treeview#3]
I can not use bower in my environment, so I got this ERROR :
>npm install react-bootstrap-treeview --save-dev
> react-bootstrap-treeview@0.1.0 install /home/ccchu/WebstormProjects/bayes/web/node_modules/react-bootstrap-treeview
> bower install
sh: 1: bower: not found

Can you help me?

**Comment by jonmiles** [comment]
If you want compile the distributable...

Manually remove bower references from package.json (scripts + devDependencies)

Then run...
$ npm install
$ grunt 

This will compile the distributable, you won't be able to run the project unless you manually replace the bower references in public/ .

**Comment by chuchengcao** [comment]
I will try it. Thank you for reply!
